config/routes.rb
Rails.application.routes.draw do
  resources :metrics
  resources :sql_queries
  resources :data_sources
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sql_query.rb
class SqlQuery < ApplicationRecord
	belongs_to :data_source
	has_many :metrics
end

app/controllers/sql_queries_controller.rb
class SqlQueriesController < ApplicationController
  before_action :set_sql_query, only: [:show, :edit, :update, :destroy]

  # GET /sql_queries
  # GET /sql_queries.json
  def index
    @sql_queries = SqlQuery.all
  end

  # GET /sql_queries/1
  # GET /sql_queries/1.json
  def show
  end

  # GET /sql_queries/new
  def new
    @sql_query = SqlQuery.new
  end

  # GET /sql_queries/1/edit
  def edit
  end

  # POST /sql_queries
  # POST /sql_queries.json
  def create
    @sql_query = SqlQuery.new(sql_query_params)

    respond_to do |format|
      if @sql_query.save
        format.html { redirect_to @sql_query, notice: 'Sql query was successfully created.' }
        format.json { render :show, status: :created, location: @sql_query }
      else
        format.html { render :new }
        format.json { render json: @sql_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sql_queries/1
  # PATCH/PUT /sql_queries/1.json
  def update
    respond_to do |format|
      if @sql_query.update(sql_query_params)
        format.html { redirect_to @sql_query, notice: 'Sql query was successfully updated.' }
        format.json { render :show, status: :ok, location: @sql_query }
      else
        format.html { render :edit }
        format.json { render json: @sql_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sql_queries/1
  # DELETE /sql_queries/1.json
  def destroy
    @sql_query.destroy
    respond_to do |format|
      format.html { redirect_to sql_queries_url, notice: 'Sql query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sql_query
      @sql_query = SqlQuery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sql_query_params
      params.fetch(:sql_query, {})
    end
end

app/helpers/sql_queries_helper.rb
module SqlQueriesHelper
end

app/views/sql_queries/_form.html.erb
<%= form_with(model: sql_query, local: true) do |form| %>
  <% if sql_query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sql_query.errors.count, "error") %> prohibited this sql_query from being saved:</h2>

      <ul>
      <% sql_query.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sql_queries/edit.html.erb
<h1>Editing Sql Query</h1>

<%= render 'form', sql_query: @sql_query %>

<%= link_to 'Show', @sql_query %> |
<%= link_to 'Back', sql_queries_path %>

app/views/sql_queries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sql Queries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sql_queries.each do |sql_query| %>
      <tr>
        <td><%= link_to 'Show', sql_query %></td>
        <td><%= link_to 'Edit', edit_sql_query_path(sql_query) %></td>
        <td><%= link_to 'Destroy', sql_query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sql Query', new_sql_query_path %>

app/views/sql_queries/new.html.erb
<h1>New Sql Query</h1>

<%= render 'form', sql_query: @sql_query %>

<%= link_to 'Back', sql_queries_path %>

app/views/sql_queries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sql_query_path(@sql_query) %> |
<%= link_to 'Back', sql_queries_path %>