config/routes.rb
Rails.application.routes.draw do
  resources :metrics
  resources :sql_queries
  resources :data_sources
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/metric.rb
class Metric < ApplicationRecord
	belongs_to :sql_query
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_action :set_metric, only: [:show, :edit, :update, :destroy]

  # GET /metrics
  # GET /metrics.json
  def index
    @metrics = Metric.all
  end

  # GET /metrics/1
  # GET /metrics/1.json
  def show
  end

  # GET /metrics/new
  def new
    @metric = Metric.new
  end

  # GET /metrics/1/edit
  def edit
  end

  # POST /metrics
  # POST /metrics.json
  def create
    @metric = Metric.new(metric_params)

    respond_to do |format|
      if @metric.save
        format.html { redirect_to @metric, notice: 'Metric was successfully created.' }
        format.json { render :show, status: :created, location: @metric }
      else
        format.html { render :new }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metrics/1
  # PATCH/PUT /metrics/1.json
  def update
    respond_to do |format|
      if @metric.update(metric_params)
        format.html { redirect_to @metric, notice: 'Metric was successfully updated.' }
        format.json { render :show, status: :ok, location: @metric }
      else
        format.html { render :edit }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.json
  def destroy
    @metric.destroy
    respond_to do |format|
      format.html { redirect_to metrics_url, notice: 'Metric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metric
      @metric = Metric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metric_params
      params.fetch(:metric, {})
    end
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/metrics/_form.html.erb
<%= form_with(model: metric, local: true) do |form| %>
  <% if metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% metric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/metrics/edit.html.erb
<h1>Editing Metric</h1>

<%= render 'form', metric: @metric %>

<%= link_to 'Show', @metric %> |
<%= link_to 'Back', metrics_path %>

app/views/metrics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Metrics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @metrics.each do |metric| %>
      <tr>
        <td><%= link_to 'Show', metric %></td>
        <td><%= link_to 'Edit', edit_metric_path(metric) %></td>
        <td><%= link_to 'Destroy', metric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metric', new_metric_path %>

app/views/metrics/new.html.erb
<h1>New Metric</h1>

<%= render 'form', metric: @metric %>

<%= link_to 'Back', metrics_path %>

app/views/metrics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_metric_path(@metric) %> |
<%= link_to 'Back', metrics_path %>